function func = function_choose(j)
    % 定义一个包含匿名函数的单元数组
    functions = {
        @(x, y, z) uint32(bin2dec(plus1(nega(add0(...
              dec2bin(bitxor(uint32(z),uint32(...
              bin2dec(plus1(nega(add0(...
              plus1(nega(add0(dec2bin(...
              bitxor(uint32(x),uint32(y)))))))))))))))))),...
        @(x, y, z) uint32(bin2dec(plus1(nega(add0(...
              dec2bin(bitor(uint32(...
              bitand(uint32(x),uint32(y))),...
              uint32(bin2dec(plus1(nega(add0(...
              plus1(nega(add0(dec2bin(...
              bitand(uint32(z),uint32(bin2dec(add0(...
              plus1(nega(add0(dec2bin(x+1)))))))))))))))))))))))),...
        @(x, y, z) uint32(bin2dec(plus1(nega(add0(...
              dec2bin(bitxor(uint32(z),...
              uint32(bin2dec(plus1(nega(add0(...
              plus1(nega(add0(dec2bin(...
              bitor(uint32(x),uint32(...
              bin2dec(add0(plus1(nega(add0(...
              dec2bin(y+1)))))))))))))))))))))))),...
        @(x, y, z) uint32(bin2dec(plus1(nega(add0(...
              dec2bin(bitor(uint32(...
              bitand(uint32(x),uint32(z))),...
              uint32(bin2dec(plus1(nega(add0(...
              plus1(nega(add0(dec2bin(...
              bitand(uint32(y),uint32(bin2dec(add0(...
              plus1(nega(add0(dec2bin(z+1)))))))))))))))))))))))),...
        @(x, y, z) uint32(bin2dec(plus1(nega(add0(...
              dec2bin(bitxor(uint32(x),uint32(...
              bin2dec(plus1(nega(...
              add0(plus1(nega(add0(...
              dec2bin(bitor(uint32(y),uint32(...
              bin2dec(add0(plus1(nega(add0(...
              dec2bin(z+1))))))))))))))))))))))))...       
    };
    % 根据 j 的值选择相应的函数
    if j <= 16
        func = functions{1};
    elseif j <= 32
        func = functions{2};
    elseif j <= 48
        func = functions{3};
    elseif j <= 64
        func = functions{4};
    elseif j <= 80
        func = functions{5};
    end
end
